### Lista Usuarios
GET http://127.0.0.1:3000/api/usuario

### Guardar usuario
POST http://127.0.0.1:3000/api/usuario
Content-Type: application/json

{
    "username": "oscar",
    "email": "oscar@gmail.com",
    "password": "oscar54321"    
}
